### ISSUE TITLE
How do I update...

### ISSUE THREAD

**Issue by EdwardElric64** [WilliamLCobb/iNDS#102]
Ok, so I have seen people say they compiled inds and updated it, but from what I have seen to compile an update I need Xcode, and also I have seen that is only for Mac, and I don't have Mac, so do you publish updates online or would I have to do it my self somehow? This isn't really an issue, I just kinda wanna know for future reference.

**Comment by DarknesGaming** [comment]
@WilliamLCobb publishes updates. On Cydia. You have to jailbreak for Cydia.
You can install VMWare Workstation Player and download Mac OS X El Capitan virtual disk from xBytez. Since it's in 7z, you'll need to get 7-zip to extract the stuff needed. Also, follow the instructions when you're doing that. You can search all of this up on Google.

**Comment by WilliamLCobb** [comment]
Cydia: Redownload
BuildStore: Redownload
XCode: Redownload the source and run it
iEmulators: Wait for newest update to be published... which could be awhile

**Comment by DarknesGaming** [comment]
Those work too.
