### ISSUE TITLE
iNDS crashes when opening 

### ISSUE THREAD

**Issue by rmiller757** [WilliamLCobb/iNDS#117]
iPhone 6 
ios 9.3.1
Nonjailbroken
iEmulators
1.3.5

I was playing , saved my game , and exited the app as usual. Upon reopening , the app crashes everytime. Any help ? 

I havnt been able to synchronize onto Dropbox so I hope I don't lose all my data if I have to reinstall it.

**Comment by WilliamLCobb** [comment]
Crashlytics doesn't work on enterprise certificates so when iNDS crashes, Crashlytics tries to send the report. However, since it doesn't work, it crashes again generating another report and the cycle never stops. I removed it in 1.5.0 but iEmulators still has an old version. The only way to fix it is to upgrade using XCode or another method like the buildstore. Or to just wait

**Comment by rmiller757** [comment]
What's Xcode ?
