### ISSUE TITLE
iNDS sound not working

### ISSUE THREAD

**Issue by idontlikes** [WilliamLCobb/iNDS#151]
my apps work but there is no sound please help.

**Comment by idontlikes** [comment]
the sound ist disabled and my volume is up

**Comment by idontlikes** [comment]
*isn't

**Comment by essiw** [comment]
Firstly, you can edit your messages, secondly as mentioned you should post this information so that we can help you:

iOS device
iOS version
Jailbreak status
Download location
Current iNDS Version

Thirdly are you sure it is not already addressed in other issues? like 
https://github.com/WilliamLCobb/iNDS/issues/139
or
https://github.com/WilliamLCobb/iNDS/issues/96

**Comment by idontlikes** [comment]
i had my ringer on mute and i guess that was the problem, thank you!
