### ISSUE TITLE
crashes before it opens

### ISSUE THREAD

**Issue by yad123** [WilliamLCobb/iNDS#181]
i am using:
iphone 6s
ios 9.3.3 (latest)
not jailbroken
github version of inds
latest version of inds
I installed the app using xcode about last week and it has been working, playing pokemon black 2, until today. It crashes as soon as i start the app. Im not sure what to do, and im confused as how to update or fix the app. The first time i used xcode was when i installed the app, so i have little knowledge on how to use it. What do i do?
Nevermind fixed by repeating the building process

**Comment by benihana7** [comment]
I had the same problem. I found out this is because the free developer account will only let you side-load the app for 7 days. After 7 days your MDM certificate trust will expire and the app will crash when you try to open it. Solution is to transfer your save state files back on your computer, re-build the iNDS using Xcode, and transfer back your save states and Roms.
