### ISSUE TITLE
"Only a limited set of users can get access tokens while this app is in development mode." when trying to link to Dropbox.

### ISSUE THREAD

**Issue by Zenivo** [WilliamLCobb/iNDS#3]
iOS device: iPhone 6S
iOS version: 9.1
Jailbreak status: Not jailbroken
Download location: Here on Github, sideloaded using Xcode

Whenever I try to log in to Dropbox, it gives the error above. Can this be fixed or is this because it's still being developed?

**Comment by WilliamLCobb** [comment]
Yea GitHub is being a bitch and not approving my app. It should fix itself in a few days

Sent from Outlook




On Sun, Nov 29, 2015 at 1:21 AM -0800, "Zenivo" <notifications@github.com> wrote:












iOS device: iPhone 6S

iOS version: 9.1

Jailbreak status: Not jailbroken

Download location: Here on Github, sideloaded using Xcode



Whenever I try to log in to Dropbox, it gives the error above. Can this be fixed or is this because it's still being developed?

**Comment by Zenivo** [comment]
Alright, I see. Thanks for the app!
