### ISSUE TITLE
Different Import Package Types

### ISSUE THREAD

**Issue by kingriddle123** [WilliamLCobb/iNDS#72]
I have iFile and I have had countless issues with importing different types of files. That's the only problem I have so far. Is there a way to import roms in rar or 7z or even .nds format? And another issue was when I tried to import these files, they clog the cache and use up space. I use icleaner pro and it can't clean out these files. I found the imported games in the data folder of iNDS under Inbox. The files that failed to import were just sitting there. They were copied and had to be manually deleted. Please add a clear cache or clear inbox button to remove these files. Thanks

**Comment by DarknesGaming** [comment]
Just place the ROMs that are in .nds format in the root of the iNDS folder. Maybe the app will then recognize the ROM and you can play it. Maybe it will work with 7z and rar because I did find files that can probably open both of those in the source code.
@WilliamLCobb might be too busy handling other problems.

**Comment by essiw** [comment]
I think this is already implemented

**Comment by WilliamLCobb** [comment]
Yep this should be working now
