### ISSUE TITLE
Speed 4x issue

### ISSUE THREAD

**Issue by hector0406** [WilliamLCobb/iNDS#84]
Hi,

I've tried some games and noticed that [Speed 4x] does not work as flawlessly as [Speed 2x]. In fact, 2x is smoother and faster than 4x.

Would there be any possibility to add [Speed 1.5x]? So games could run a little bit faster but the music.

**Comment by WilliamLCobb** [comment]
The problem is every single frame has to run. Speedups would work really well if we could run the calculations of 2 frames at once. Anyways the reason games run worse at 4x speed is because the phone is trying to run 4 frames in 1 second and then update the display. If it can't finish all 4 frames (which no device I know of can), you see the game lag and a sharp fps drop.

tl;dr until phones get faster, 4x speed will suck.

Also I like the idea of 1.5 speed. It won't be hard at all to put it in there. I'll do that for the next release

**Comment by WilliamLCobb** [comment]
I added a few things to increase fps for 4x speed. It won't be perfect until faster devices are released though. I'll add 1.5 speed soon
