### ISSUE TITLE
iNDS keeps creating pause files, even when not playing, causes crashing

### ISSUE THREAD

**Issue by essiw** [WilliamLCobb/iNDS#88]
I am not sure if this problem is already known, but it seems like more people have issues about crashing. After crashing the only way to fix it is by reinstalling the app. I have found the problem to this crashing.

When you are in a game and press on settings the game starts making pause files endlessly (even when you do nothing). Even when you have the setting "periodic save" off. After a while, or sometimes when you try to remove the amount of pause files (I have had more than 15) the app crashes and keeps crashing when you try to open it. It even goes on making pause files for that particular game if you switch to an other game.

I came to this problem because I was trying to run my some of my games (pokemon) more smoother for issue #86, which didn't work in the end.

I would like to suggest to stop making pause files if you have the option "periodic save" off. And of course try to fix this problem ;) I appreciate the time you spend to make this emulator working.

iOS device: iPad Air 1
iOS version: 9.3.1
Jailbreak status: None
Download location: builds.io
Current iNDS Version: 1.4.0.

**Comment by DarknesGaming** [comment]
Must be a bug in iNDS. I am also experiencing the same problem. @WilliamLCobb will probably fix this ASAP, but this is coming from someone who found over 400 issues while building iNDS through Xcode.

**Comment by DarknesGaming** [comment]
Also, this is a reason why I came up with the beta branch idea: To find bugs in iNDS, fix them, and then release them to the public. If you need an example, take the Apple Beta Software Program.

**Comment by DarknesGaming** [comment]
Edit: ...and then release the app to the public.

**Comment by WilliamLCobb** [comment]
Does it make the pause files in dropbox or your local folder? I just started doing that in the latest version. When you pause the game it creates a save file

**Comment by DarknesGaming** [comment]
If you turn on periodic save, every time you press a button (D-Pad, ABXY buttons or LR bumpers), the app will save immediately. That should be obvious when the save states say "Pause (XXX)", where X is supposed to be a number. I roamed through my save states and found that the app saved 10 times in a minute. This kept on going, even when I was playing the ROM.
I just looked at my Dropbox and there are WAY too many save states for the same game. So in a way, this is happening both in Dropbox AND the local folder. This would be more of a critical bug if you're running iNDS on a device that is running out of storage.
I'm sure @WilliamLCobb will fix this. Maybe there will be an iNDS 1.4.1 to fix this and a bunch of other bugs. And I'll have to go through the trouble of building that through Xcode because I can't afford to get a BuildStore account.

**Comment by essiw** [comment]
@WilliamLCobb it creates them in my dropbox folder. I am not sure if it also creates them in my local folder. Anyway, one way to fix this would be to override the last pause file when you pause the game, instead of creating a new one. Especially as you are able to get back past versions of the file via dropbox history ;)

**Comment by DarknesGaming** [comment]
Wow. You are really active on GitHub essiw. I should congratulate you.
I'm going to hope you don't have over 300 save files for the same game. Best way to find out if it's happening in the local folder is if you plug the iPad into your computer, launch iTunes, go into your device, click "Apps" and scroll to the bottom. Then download the "Documents" folder.

**Comment by essiw** [comment]
@DarknesGaming I am only active on this github, as I came across these bugs while trying to play games. I don't have any pause files in my games, as I do not pause my game anymore in order to avoid this bug and having to install the app again, so these local files have been deleted the last time this happened. I also deleted all the pause files in dropbox before reloading my game data in the app.

**Comment by WilliamLCobb** [comment]
It should be overwriting the save files locally when the game pauses. I think the reason there are 100 pause files is a bug in the dropbox library. The library uploads the file and check for it and dropbox says it's not there and repeats the process until you close the app. 

I should be able to add a double check to make sure the file is not there before uploading or prevent uploading the same file twice.

**Comment by WilliamLCobb** [comment]
A temporary solution would be to disable dropbox for the time being

**Comment by essiw** [comment]
Great :) Thanks a lot. 

I actually use an other temporary solution. I do not pause the app and force quit the app when I want to change games.

**Comment by DarknesGaming** [comment]
I tried turning periodic save off. That actually made iNDS stop saving every few seconds while I played the game. What I don't know is why it made more pause save files instead of overwriting the existing one instead.
Probably a bug in periodic save. It's definitely affecting the local folder because I don't think an app with only 3 games that total up to 500 MB would take up 1.2 GB of space. I blame the excessive amounts of save files iNDS created due to a bug that is linked to Periodic Save.
If you don't believe me, turn off periodic save right now, and see what happens.

**Comment by DarknesGaming** [comment]
And seriously, plug your device into your computer, launch iTunes, view your device status, and go to the Apps section. Scroll down to the Documents and Data section, click on iNDS and download the Documents folder. This really doesn't seem like a dropbox issue because nds4ios overwrites save files on dropbox all the time. And since iNDS is based on that, iNDS should do the same thing.
Not convinced that this is a periodic save bug? Then I must be REALLY crazy.

**Comment by Anuskuss** [comment]
@DarknesGaming If you really think that it *must* be a problem with Periodic Save you're free to look into the source code, create a branch and present it to @WilliamLCobb. If you are not capable of doing so (and I'm afraid you are), let @WilliamLCobb do his thing.
He already stated that it is a problem with Dropbox, and he's doing his best to fix it. You won't really help him with your theroies about Periodic Save or by saying that you found 300+ issues in Xcode (like he doesn't know).
So please give him a rest and relax.

Btw @WilliamLCobb, the syncing doesn't have to be asap. Maybe upload the save files only after the game/app was closed (if that is possible)?

**Comment by DarknesGaming** [comment]
I actually use that source code. The 300 issues is not important at all anymore, so let's just drop it.
I'll just do my best to find a way to fix the excessive save state problem from periodic save. Maybe the feature recognizes the interval as seconds and not minutes. Dropbox automatically overwrites older save files with newer ones that have the same name and extension, so it can't be Dropbox with this problem.

**Comment by Anuskuss** [comment]
@DarknesGaming Did you atleast tried do deactivate Dropbox sync and watch the result (since that is a temporary workaround)?

**Comment by DarknesGaming** [comment]
@Anuskuss I am going to try that. First, I need to delete all the unnecessary save files from iNDS and Dropbox. Then I need to see if my new pause file overwrites the older one when iNDS syncs with dropbox.

**Comment by DarknesGaming** [comment]
iNDS is updated to 1.4.0.2 or 1.4.1. Time to build this with Xcode.

**Comment by DarknesGaming** [comment]
Forget everything I have ever said about Periodic save being buggy. I am crazy.
This is truly a Dropbox problem. I think @WilliamLCobb fixed this last night, and what's weird is that it syncs while you're playing a ROM. Is there any way you can make the app only sync when not playing a ROM?

**Comment by WilliamLCobb** [comment]
Should be fixed in 1.5.0 which is coming out soon. Please reopen if it's not
