### ISSUE TITLE
Changing Resolution?

### ISSUE THREAD

**Issue by defex10** [WilliamLCobb/iNDS#91]
Hey,

are there any plans to change the display resolution to get better graphics? (like the DraStic Emulator for Android?)

**Comment by DarknesGaming** [comment]
@defex the resolution depends on your device. Getting better graphics would mean applying filters found inside the DeSmuME 0.9.10 files, but that will probably be added in iNDS 1.5.0. For now, we can test that feature in the beta branch, when we add it.
@WilliamLCobb what do you think?

**Comment by DarknesGaming** [comment]
Sorry. @defex10 lol

**Comment by defex10** [comment]
Yeah, I was talking about the filters :P
Can I get the beta directly on my device? (Cydia?)

**Comment by essiw** [comment]
I think you can build the beta if you own a mac (or use virtual machine) and have a free developers account and run it directly. However I do not think WilliamLCobb has actually implemented those options in the beta version yet (or I missed something), and I am not sure whether he is planning to do so in the near future.

**Comment by DarknesGaming** [comment]
The beta will probably be on Cydia when @WilliamLCobb has time. For now, just keep waiting @defex10. Maybe something will be ready.

**Comment by WilliamLCobb** [comment]
Adding the bicubic interpolation option (rather than the regular linear) was my first attempt at increasing the resolution but it ended up not really doing anything. 

If I can figure out how to change the internal resolution in DeSmuME I'll add that as an option

**Comment by DarknesGaming** [comment]
I think the resolution is determined by your device. You can try making the graphics look sharper though.

**Comment by DarknesGaming** [comment]
Also, shouldn't the beta branch have the commits the master branch has?

**Comment by iOSSOi** [comment]
Would really be nice to change to a higher res, would give alot of replay value to games. Crazy good progress on the emulator so far, thx for the great development!

**Comment by DarknesGaming** [comment]
I agree with @iOSSOi. You have been making extremely good progress with the emulator @WilliamLCobb! It's not as choppy as nds4ios, which is good.
We can't go past the device resolution limit, but the filters can be applied to make the game look sharper.
That's it! Why don't you just add an option where you can apply filters? That would be awesome. And iNDS 1.5.0 does not have a significant change log.

**Comment by iOSSOi** [comment]
Playing iNDS alot on my ipad pro since yesterday, all the micro stuttering is gone! You are truly amazing @WilliamLCobb. I don't know if it's the commit regarding the changes to how the emulator now handles throttle, but every game i throw at this emulator runns like buttery smooth, the finest butter!

@DarknesGaming basically all iOS devices able to run inds smoothly today, have alot higher screen resolution than the what NDS provides physically. I dont know how hevy it would be on the hardware to run the same method as PPSSPP [ 1xPSP RES, 2xPSP RES and so on, maybe up to 5xPSP RES].

@WilliamLCobb what do you think big boss, am i speculating all wrong or is this something that can be added the same way PPSSPP has it implemented? [ 1xINDS RES, 2xINDS RES and so on, up to what you consider necessary]

**Comment by defex10** [comment]
Just updated to 1.5.0 and saw the new FPS counter.
Great to see that the games run so smooth!
Maybe a FPS-Lock would be good for the new devices?
And filter like linear, scale2x, hq2x...

**Comment by WilliamLCobb** [comment]
It is definitely possible to increase the internal resolution but it will require some work. This is pretty high on my list because a Nintendo DS with retina resolution would be amazing.

I tried taking the finished image and applying a bicubic filter to it but I can't really tell the difference.

Filters would need to be applied to individual textures and DeSmuME would need to be configured to not scale down the resolution

**Comment by DarknesGaming** [comment]
*continues to wait*

**Comment by WilliamLCobb** [comment]
Got it working and it looks really good. It's pretty slow so I'm going to have to figure out a way to offload it to the GPU but retina resolution looks really cool

**Comment by Anuskuss** [comment]
Is it ready for the beta branch (or however you want to handle betas)?

**Comment by iOSSOi** [comment]
yeeeeeeeeess, this is it! Dragon quest and golden sun, Zelda ST, KH 352/2 high res... Please tell me how I can donate money to this project

**Comment by WilliamLCobb** [comment]
Don't worry about donations right now. A thank you means a lot more than a donation. But thank you for the offer.

Here are some example filters. It's a little hard to see the improvement in a single picture but it looks quite a bit better

![img_0701](https://cloud.githubusercontent.com/assets/870904/14656429/1ced4f16-064d-11e6-9919-c8d7d4e01d53.PNG)
![img_0702](https://cloud.githubusercontent.com/assets/870904/14656432/1ceddf30-064d-11e6-8fd7-64ce177de6f7.PNG)
![img_0703](https://cloud.githubusercontent.com/assets/870904/14656433/1cee4bc8-064d-11e6-879b-961d7ec3272d.PNG)
![img_0704](https://cloud.githubusercontent.com/assets/870904/14656430/1ced8242-064d-11e6-89ff-82801bf47398.PNG)
![img_0707](https://cloud.githubusercontent.com/assets/870904/14656431/1ced75fe-064d-11e6-893f-360a609f85bd.PNG)

**Comment by iOSSOi** [comment]
Ok, maybe no donations at this point, maybe a pizza?

**Comment by DarknesGaming** [comment]
Those filters do make the game look better. What about the Depth Threshold for the shadows?

**Comment by iOSSOi** [comment]
Yes yes yes yes yeeeeeeeeeeeeees, its finally here!!! Any release so we can test the results?

**Comment by WilliamLCobb** [comment]
Yep I just updated the source on GitHub. If you can sideload just redownload and install. 

I added a new one called BRZ which looks a lot better than the filters I posted here but runs really really slow.

**Comment by defex10** [comment]
Cydia update would be nice :)

**Comment by iOSSOi** [comment]
I dont have an osx comp, could you maybe make an ipa update here: https://github.com/WilliamLCobb/iNDS/releases

And please man, let be buy you a pizza or something else. Please!! I sure cant code, but my conscience is killing me for not doing anything. Please, atleast something!

**Comment by DarknesGaming** [comment]
I have never heard of the BRZ filter before. Must be new.
The filter looks like it enlarges the top screen and not the bottom. Is that on an iPad?

**Comment by DarknesGaming** [comment]
@iOSSOi I know you want to give @WilliamLCobb something because you appreciate his work, but I think you're going nuts about it. You're already giving him appreciation right now.
Speaking of which, I appreciate your work @WilliamLCobb. iNDS just keeps better and better because of your hard (and probably painful) work. :smile:

**Comment by iOSSOi** [comment]
True, very true. I am going nuts about it. He is donating hisntime for something no one of us deserves, the least thing i can do is to offer himma meal. I really want him to enjoy the time he is developing the emulator. Hey @WilliamLCobb , if you want to i would be happy so send you my first gen NDS if it would be any help for development. Its not much, but it still works. Of cource for free.

**Comment by DarknesGaming** [comment]
Wow. You're up to the point of donating a rare treasure built from the factories of Nintendo. I'm sure @WilliamLCobb is enjoying his time developing the emulator, and if he isn't, he would be a LOT less active on development. He did try to fix the Pokemon HeartGold/SoulSilver thing (black screen) though.

**Comment by DarknesGaming** [comment]
Turns out DeSmuME 0.9.11 has 4 BRZ filters, starting from 2x to 5x. It also has a bunch of other filters not included with 0.9.10, which means more ways of making your game look cool! That may affect the game performance though.
High-resolution 3d rendering exists, but you would need to use DeSmuME SVN r5268 or later. Maybe that could help with the Ace Attorney problem someone was experiencing a few days back, and make the game look better. I'm not sure if old devices will be able to handle that.
@WilliamLCobb what do you think?

**Comment by DarknesGaming** [comment]
Updating DeSmuME to an SVN build would be hard, because those are more like nightly builds than stable builds. Plus, the code must be modified for use with iOS, followed by extensive testing, bug fixes, and @defex10 giving us suggestions.

**Comment by DarknesGaming** [comment]
Are we able to apply filters yet? I am getting tired of being able to see all those pixels, and the only game I'm going to tolerate seeing pixels is Minecraft. xD

**Comment by DarknesGaming** [comment]
The changing resolution is complete. We no longer need to worry about it.
We can close this issue.
