### ISSUE TITLE
iNDS crashes when i open it.

### ISSUE THREAD

**Issue by Levinsky10** [WilliamLCobb/iNDS#93]
Iphone 6
9.2 
Unjailbroken

(Im not sure which version but i downloaded it yesterday)

So i downloaded iNDS yesterday with pokemon black 2 and started playing and as soon as i got into the game it just crashed so i didnt think Much of it and restarted my phone but from that point the app would crash as soon as i open it. Would appreciate any help at all.

**Comment by essiw** [comment]
First, it might be handy to give a bit more info as to where you downloaded it from, did you downloaded it from a website like builds.io or did you sideload it?
Secondly make sure you have a back-up of your files either by dropbox synch or by taking via iTunes in order to prevent progress from your game.
Then just redownload the game. You might want to try redownloading it while the game is still there, to save time setting up your game and such. If that does not work then delete the app and redownload the app and it should work again :) 

Also I don't know if you could give a more thorough description of what happened before the crashing happened? It might be something that @WilliamLCobb could fix to prevent it from happening in the future :) My guess is that it probably has to do something with synching files. Did you enable dropbox synching?

**Comment by Levinsky10** [comment]
I downloaded the emulator from iemulator.com  As soon as i opened the game for the first time ( first game ever to open in the emulator) it crashed and it keeps crashing as soon as i open it. I reinstalled the app and it didnt make any difference. (p.s if anyone knows a gba emulator for iphone 9+ i would greatly appreciate it)

**Comment by essiw** [comment]
In that case it might just be the case that the certificate signed by apple for iNDS created by iemulators has been revoked. I would suggest to contact iemulators instead. The only (and is probably the best one) gba emulator that I know of is GBA4iOS.

**Comment by Levinsky10** [comment]
GBA4IOS Doesnt work for me would you know a way to get it?

**Comment by essiw** [comment]
There are a few ways:
You can download it from http://builds.io (you need to pay 10 dollars for it to work one **one** device for a **year** but then you can use all apps on there, including iNDS) I do it that way. 
You can sideload the app (downloading it from github), though I do not know where to find GBA4iOS github. Refer to the wiki for more info, this works also for iNDS.
You can jailbreak your device and install a program that ignores the need to sign apps, use google/duckduckgo to find out how, and then install the app via a website.

**Comment by Levinsky10** [comment]
Is it possible to pay in another way than paypal? I'm too young to have a credit card that works on the internet and my parents hate paying through the internet.

**Comment by essiw** [comment]
I am sorry to say but this github is about iNDS, I answered the previous post because those methods work for iNDS as well. Please go for other questions to the makers or websites concerning these problems. Also as you specified that you are of a young age you might want to ask your parents if they allow this, because while these emulators are not illegal, downloading ROMS of games you do not own is illegal.

**Comment by Levinsky10** [comment]
Alright well, thanks alot anyways ill be trying to get my iNds to work again i suppose.

**Comment by DarknesGaming** [comment]
@Levinsky10 I feel very sorry for what has happened to you. Unfortunately, iEmulators most likely have not grabbed the latest version of iNDS yet (1.5.0), and the certificate was revoked months ago.
The only free way to get this for real is to use a Mac, either purchased or through VMware. Refer to the wiki on how to build iNDS for Jailed devices for further instructions.

**Comment by DarknesGaming** [comment]
Our most current iNDS version most likely won't crash, and updating from iOS 9.2 to 9.3.1 is recommended because jailbreak teams are probably not focusing on 9.2 anymore.

**Comment by OkazakiTheOtaku** [comment]
@DarknesGaming I'm not trying to start an argument, but it is worth noting that Pangu released a jailbreak for 9.1 way after 9.2 was released.

**Comment by DarknesGaming** [comment]
@OkazakiTheOtaku you are right about Pangu. They did release a jailbreak for iOS 9.1, but there aren't a lot of people on that version, and it only works on 64-bit devices.
There's a reason for what I said in my last comment: Pangu may have already jailbroken iOS 9.2. They also may have already jailbroken iOS 9.2.1, 9.3, 9.3.1 and now working on 9.3.2. The tool isn't released because they're waiting for the right time.

**Comment by WilliamLCobb** [comment]
Unfortunately iEmulators signed a broken version that does this. After the app crashes for the first time, crashlytics tried to send me the crash report. However iemulators and the buildstore change the signature and this causes crashlytics to crash. The only fix is redownloading the app to delete the crash log.

This was fixed in the latest version but iEmulators in still using a bugged earlier version.
