### ISSUE TITLE
[request] 3ds support

### ISSUE THREAD

**Issue by GrumpyOet** [WilliamLCobb/iNDS#95]
WilliamLCobb can you let iNDS support 3ds games

(you can use citra-emu)

**Comment by DarknesGaming** [comment]
WHAT?!
How would you do that? A 3DS emulator is much more resource demanding than a DS emulator. Plus, @WilliamLCobb will have to grab the source code of the emulator you've chosen (Citra-emu), and tinker with it so that it works with iOS without crashing.
Plus, there are only nightly builds right now, which are not stable builds.

**Comment by pmp174** [comment]
The emulator is still in development. Until the emulator starts working the app is unlikely to get it.

**Comment by WilliamLCobb** [comment]
As mentioned, Citra is still in early development. Also iOS has no virtual memory which makes it really hard to port emulators. This is also the main reason why Dolphin isn't on iOS.

It may happen eventually but it will be years before we see a 3ds emulator on iOS
